# Name : MOQORU(Youngjune Seo)
import numpy as np
A = np.array([1,2,3,4])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6]])
print(A)
print(B)
print(np.ndim(A), np.ndim(B))
print(A.shape, B.shape)
print(A.shape[0], B.shape[0])
print(C.shape)
print(np.dot(B,C))
print(np.dot(C,B))
print(np.dot(A,C))
